export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_RELOGIN_WARNING_MODAL = 'SET_RELOGIN_WARNING_MODAL';
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

export const GET_IDENTITIES = 'GET_IDENTITIES';
export const GET_IDENTITIES_SUCCEEDED = 'GET_IDENTITIES_SUCCEEDED';
export const GET_IDENTITIES_FAILED = 'GET_IDENTITIES_FAILED';

export const GET_MY_RESERVATIONS = 'GET_MY_RESERVATIONS';
export const GET_MY_RESERVATIONS_SUCCEEDED = 'GET_MY_RESERVATIONS_SUCCEEDED';
export const GET_MY_RESERVATIONS_FAILED = 'GET_MY_RESERVATIONS_FAILED';

export const GET_CONSTRUCTIONS = 'GET_CONSTRUCTIONS';
export const GET_CONSTRUCTIONS_SUCCEEDED = 'GET_CONSTRUCTIONS_SUCCEEDED';
export const GET_CONSTRUCTIONS_FAILED = 'GET_CONSTRUCTIONS_FAILED';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_TIME_SLOT = 'SELECT_TIME_SLOT';
export const SET_LICENSE_PLATE_NUMBER = 'SET_LICENSE_PLATE_NUMBER';
export const SET_MATERIAL = 'SET_MATERIAL';

export const SET_RESERVATION = 'SET_RESERVATION';
export const SET_RESERVATION_SUCCEEDED = 'SET_RESERVATION_SUCCEEDED';
export const SET_RESERVATION_FAILED = 'SET_RESERVATION_FAILED';
export const CLEAN_RESERVATION = 'CLEAN_RESERVATION';

export const SET_MY_RESERVATIONS_FILTER = 'SET_MY_RESERVATIONS_FILTER';
export const SET_MY_RESERVATIONS_SHOWING_RESERVATION_ID = 'SET_MY_RESERVATIONS_SHOWING_RESERVATION_ID';

export const GET_ALL_RESERVATIONS = 'GET_ALL_RESERVATIONS';
export const GET_ALL_RESERVATIONS_SUCCEEDED = 'GET_ALL_RESERVATIONS_SUCCEEDED';
export const GET_ALL_RESERVATIONS_FAILED = 'GET_ALL_RESERVATIONS_FAILED';
export const SET_ALL_RESERVATIONS_FILTER = 'SET_ALL_RESERVATIONS_FILTER';
export const SET_ALL_RESERVATIONS_SHOWING_RESERVATION_ID = 'SET_ALL_RESERVATIONS_SHOWING_RESERVATION_ID';

export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const UPDATE_RESERVATION_SUCCEEDED = 'UPDATE_RESERVATION_SUCCEEDED';
export const UPDATE_RESERVATION_FAILED = 'UPDATE_RESERVATION_FAILED';

export const TAKE_PICTURE_SUCCEEDED = 'TAKE_PICTURE_SUCCEEDED';
export const TAKE_PICTURE_FAILED = 'TAKE_PICTURE_FAILED';

export const SET_EXPO_PUSH_TOKEN = 'SET_EXPO_PUSH_TOKEN';
export const SET_EXPO_PUSH_TOKEN_SUCCEEDED = 'SET_EXPO_PUSH_TOKEN_SUCCEEDED';
export const SET_EXPO_PUSH_TOKEN_FAILED = 'SET_EXPO_PUSH_TOKEN_FAILED';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SHOW_NOTIFICATION_SUCCEEDED = 'SHOW_NOTIFICATION_SUCCEEDED';