export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_RELOGIN_WARNING_MODAL = 'SET_RELOGIN_WARNING_MODAL';
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

export const GET_IDENTITIES = 'GET_IDENTITIES';
export const GET_IDENTITIES_SUCCEEDED = 'GET_IDENTITIES_SUCCEEDED';
export const GET_IDENTITIES_FAILED = 'GET_IDENTITIES_FAILED';

export const GET_MY_RESERVATIONS = 'GET_MY_RESERVATIONS';
export const GET_MY_RESERVATIONS_SUCCEEDED = 'GET_MY_RESERVATIONS_SUCCEEDED';
export const GET_MY_RESERVATIONS_FAILED = 'GET_MY_RESERVATIONS_FAILED';

export const GET_CONSTRUCTIONS = 'GET_CONSTRUCTIONS';
export const GET_CONSTRUCTIONS_SUCCEEDED = 'GET_CONSTRUCTIONS_SUCCEEDED';
export const GET_CONSTRUCTIONS_FAILED = 'GET_CONSTRUCTIONS_FAILED';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_TIME_SLOT = 'SELECT_TIME_SLOT';
export const SET_LICENSE_PLATE_NUMBER = 'SET_LICENSE_PLATE_NUMBER';
export const SET_MATERIAL = 'SET_MATERIAL';

export const CREATE_RESERVATION = 'CREATE_RESERVATION';
export const CREATE_RESERVATION_SUCCEEDED = 'CREATE_RESERVATION_SUCCEEDED';
export const CREATE_RESERVATION_FAILED = 'CREATE_RESERVATION_FAILED';
export const CLEAN_RESERVATION = 'CLEAN_RESERVATION';

export const SET_MY_RESERVATIONS_FILTER = 'SET_MY_RESERVATIONS_FILTER';
export const SET_MY_RESERVATIONS_SHOWING_RESERVATION_ID = 'SET_MY_RESERVATIONS_SHOWING_RESERVATION_ID';

export const GET_ALL_RESERVATIONS = 'GET_ALL_RESERVATIONS';
export const GET_ALL_RESERVATIONS_SUCCEEDED = 'GET_ALL_RESERVATIONS_SUCCEEDED';
export const GET_ALL_RESERVATIONS_FAILED = 'GET_ALL_RESERVATIONS_FAILED';
export const SET_ALL_RESERVATIONS_FILTER = 'SET_ALL_RESERVATIONS_FILTER';
export const SET_ALL_RESERVATIONS_SHOWING_RESERVATION_ID = 'SET_ALL_RESERVATIONS_SHOWING_RESERVATION_ID';

export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const UPDATE_RESERVATION_SUCCEEDED = 'UPDATE_RESERVATION_SUCCEEDED';
export const UPDATE_RESERVATION_FAILED = 'UPDATE_RESERVATION_FAILED';

export const SET_EXPO_PUSH_TOKEN = 'SET_EXPO_PUSH_TOKEN';
export const SET_EXPO_PUSH_TOKEN_SUCCEEDED = 'SET_EXPO_PUSH_TOKEN_SUCCEEDED';
export const SET_EXPO_PUSH_TOKEN_FAILED = 'SET_EXPO_PUSH_TOKEN_FAILED';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SHOW_NOTIFICATION_SUCCEEDED = 'SHOW_NOTIFICATION_SUCCEEDED';

export const UPDATE_RESERVATION_BY_NOTIFICATION = 'UPDATE_RESERVATION_BY_NOTIFICATION';
export const SET_RESERVATION_BY_NOTIFICATION = 'SET_RESERVATION_BY_NOTIFICATION';

export const GET_MONITOR_VIEW = 'GET_MONITOR_VIEW';
export const GET_MONITOR_VIEW_SUCCEEDED = 'GET_MONITOR_VIEW_SUCCEEDED';
export const GET_MONITOR_VIEW_FAILED = 'GET_MONITOR_VIEW_FAILED';

export const SET_CALENDAR_LOCATION = 'SET_CALENDAR_LOCATION';

export const SET_RESERVATION = 'SET_RESERVATION';
export const SET_PARTIAL_RESERVATIONS = 'SET_PARTIAL_RESERVATIONS';

export const ADD_NOTIFICATION_REFERENCE = 'ADD_NOTIFICATION_REFERENCE';

export const UPDATE_ALERT_STATE = 'UPDATE_ALERT_STATE';
export const UPDATE_ALERT_STATE_SUCCEEDED = 'UPDATE_ALERT_STATE_SUCCEEDED';
export const UPDATE_ALERT_STATE_FAILED = 'UPDATE_ALERT_STATE_FAILED';

export const UPDATE_ALERT_STATE_BY_NOTIFICATION = 'UPDATE_ALERT_STATE_BY_NOTIFICATION';

export const SET_USER_ACTIVE_STATE = 'SET_USER_ACTIVE_STATE';
export const SET_USER_ACTIVE_STATE_SUCCEEDED = 'SET_USER_ACTIVE_STATE_SUCCEEDED';
export const SET_USER_ACTIVE_STATE_FAILED = 'SET_USER_ACTIVE_STATE_FAILED';

export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';

export const UPDATE_RESERVATION_BY_WEBSOCKET = 'UPDATE_RESERVATION_BY_WEBSOCKET';
export const ADD_RESERVATION_BY_WEBSOCKET = 'ADD_RESERVATION_BY_WEBSOCKET';
export const UPDATE_MONITOR_VIEW_BY_WEBSOCKET = 'UPDATE_MONITOR_VIEW_BY_WEBSOCKET';

export const STORE_IMAGE = 'STORE_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';